apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: three-tier
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
        - name: api
          image: 812200312469.dkr.ecr.us-east-1.amazonaws.com/backend:35
          ports:
            - containerPort: 3500

          # ✅ probes should be here (NOT inside ports)
          livenessProbe:
            httpGet:
              path: /
              port: 3500
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 3500
            initialDelaySeconds: 5
            periodSeconds: 5

          startupProbe:
            httpGet:
              path: /
              port: 3500
            failureThreshold: 30
            periodSeconds: 10